#!/bin/sh

if [ -f "/etc/systemd/system/network-online.target.wants/NetworkManager-wait-online.service" ]; then
  sudo systemctl disable --now NetworkManager.service;
  dunstify -a "wifi" -u low -r 9994 "NetworkManager Disabled" -t 500
	pkill -RTMIN+3 "${STATUSBAR:-dwmblocks}"
else
  sudo systemctl enable --now NetworkManager.service;
  dunstify -a "wifi" -u low -r 9994 "NetworkManager Enabled" -t 500
	pkill -RTMIN+3 "${STATUSBAR:-dwmblocks}"
fi
