#!/bin/sh

# Compositor 
feh --bg-fill /home/l6b7/.static/resources/wallpapers/black.png
xcompmgr &

# Keybindings
xbindkeys -f ~/.config/x11/xbindkeysrc

# Keyboard 
xset r rate $(echo $ZK_SYS_KBD_FEEDBACK)
setxkbmap $ZK_SYS_KBD_MAP

# setxkbmap -option caps:swapescape
setxkbmap -option caps:super
setxkbmap -option shift:both_capslock
xcape -t 150 -e 'Super_L=Scroll_Lock' # swap scroll_lock with something more sensible (hold super for less than 200 ms and it will press scroll lock instead)

# Monitor
zkmon_main

#Hide mouse
if [[ "$ZK_SYS_UNCLUTTER" -eq 1 ]]; then
unclutter --timeout 4 &
fi

# Screen Brightness
brightnessctl set 100%

# Clipboard
clipmenud &

# Notifications
dunst &

# kdeconnect
/usr/bin/kdeconnectd &

# start dwmblocks
dwmblocks &

# Execute DWM
export ZK_DMENU_OPTS_DEFAULT=$(dmenu_pos)
exec dwm
# while type dwm >/dev/null ; do dwm && continue || break ; done
