Section  "InputClass"
    Identifier "/dev/input/event15"
    Driver "libinput"
    MatchIsTouchpad "on"
    Option "Tapping" "on"	
    Option "NaturalScrolling" "true"
    Option "TappingButtonMap" "lmr"
    Option "DisableWhileTyping" "0"
EndSection
